import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AdSlot } from '@/components/adsense/AdSlot';
import { ArticleCard } from '@/components/ArticleCard';
import { formatDate, getArticle, publishedArticles } from '@/lib/content';
import { siteConfig } from '@/config/site';

export function generateStaticParams() { return publishedArticles.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const article = getArticle(slug); if (!article) return {}; return { title: article.title, description: article.description, alternates: { canonical: `/articles/${slug}` }, openGraph: { type: 'article', title: article.title, description: article.description, publishedTime: article.publishedAt, modifiedTime: article.updatedAt, authors: [article.author], url: `/articles/${slug}` }, twitter: { card: 'summary', title: article.title, description: article.description } }; }
export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const article = getArticle(slug); if (!article) notFound();
  const related = publishedArticles.filter(item => item.slug !== article.slug && (item.categorySlug === article.categorySlug || item.editorPick)).slice(0, 2);
  const schema = { '@context': 'https://schema.org', '@type': 'Article', headline: article.title, description: article.description, datePublished: article.publishedAt, dateModified: article.updatedAt, author: { '@type': 'Organization', name: article.author }, publisher: { '@type': 'Organization', name: siteConfig.siteName }, mainEntityOfPage: `${siteConfig.siteUrl}/articles/${article.slug}`, image: `${siteConfig.siteUrl}${article.featuredImage}` };
  const crumbs = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: siteConfig.siteUrl }, { '@type': 'ListItem', position: 2, name: 'Articles', item: `${siteConfig.siteUrl}/articles` }, { '@type': 'ListItem', position: 3, name: article.title, item: `${siteConfig.siteUrl}/articles/${article.slug}` }] };
  return <main id="main-content"><article><header className="article-header shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/articles">Articles</Link><span>/</span><Link href={`/categories/${article.categorySlug}`}>{article.category}</Link></nav><span className="eyebrow">{article.category}</span><h1>{article.title}</h1><p className="dek">{article.description}</p><div className="article-meta"><span>Written by {article.author}</span><span>Published {formatDate(article.publishedAt)}</span>{article.updatedAt !== article.publishedAt && <span>Updated {formatDate(article.updatedAt)}</span>}<span>{article.readingTime} min read</span></div></header><div className="article-image shell"><Image src={article.featuredImage} alt="Abstract map of connected signals, evidence, and decisions" fill priority sizes="(max-width: 900px) 100vw, 1320px"/></div><div className="article-layout shell"><aside className="toc" aria-label="Table of contents"><span>On this page</span>{article.sections.map(section => <a href={`#${section.id}`} key={section.id}>{section.heading}</a>)}</aside><div className="article-body">{article.sections.map((section, index) => <section id={section.id} key={section.id}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph, p) => <p key={p}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map(bullet => <li key={bullet}>{bullet}</li>)}</ul>}{section.callout && <aside className="callout">{section.callout}</aside>}{index === 1 && <AdSlot slot="ARTICLE_MID_1" />}</section>)}{article.references.length > 0 && <section><h2>References</h2><ol>{article.references.map(ref => <li key={ref.url}><a href={ref.url} target="_blank" rel="noopener noreferrer">{ref.label}</a></li>)}</ol></section>}<p className="last-updated">Last updated {formatDate(article.updatedAt)}.</p></div></div></article><section className="related shell"><div className="section-heading"><span>Continue reading</span><h2>Related field notes</h2></div><div className="article-grid">{related.map((item, index) => <ArticleCard key={item.slug} article={item} index={index}/>)}</div></section><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }}/><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(crumbs).replace(/</g, '\\u003c') }}/></main>;
}
